# Generated by Django 5.2 on 2025-05-09 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_adminusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusers',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
